### ISSUE TITLE
Enable SSO

### ISSUE THREAD

**Issue by syphax-bouazzouni** [lifewatch-eric/ecoportal_web_ui#100]
Old documentation on how to enable it https://www.notion.so/stageportal/Ecoportal-SSO-configuration-85f90a4450104b4e9284cbe3ac1b8281?pvs=4
Need to test if it does still work.

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni private notion link in the issue description

**Comment by syphax-bouazzouni** [comment]
It is by purpose @Bilelkihal

**Comment by syphax-bouazzouni** [comment]
Done, see the screencast below, and  the public documentation here: https://stageportal.notion.site/Enable-keycloak-SSO-in-OntoPortal-13be345b80278064bdf9ee754b76f6ee?pvs=4

[Screencast from 2024-11-14 08-51-30.webm](https://github.com/user-attachments/assets/1005b578-6af0-48a4-9058-871127e1c59e)
