### ISSUE TITLE
an issue when logged using SSO to EOSC it returns to 404

### ISSUE THREAD

**Issue by syphax-bouazzouni** [lifewatch-eric/ecoportal_web_ui#101]

**Comment by syphax-bouazzouni** [comment]
@jonquet can you try again and show the screen shot I can not reproduce it.

**Comment by jonquet** [comment]
Re-testé ce matin. En passant par le login EOSC. Et cela fonctionne... je reviens vers EcoPortal loggé (apres redirection de SSO INRA, a SSO EGI, a EcoPortal)... et quand je clique "Account" je reste connecté. 

Je suggère que tu fasses un autre test avec ton compte Umontpellier

**Comment by syphax-bouazzouni** [comment]
UMOntpellier did not yet implement the EOSC SSO, same for my Berlin account.

**Comment by jonquet** [comment]
Can you @bilelkihal do the complete SSO test with connecting with your INRAE account via "EOSC login"

**Comment by Bilelkihal** [comment]
I got lost in EOSC login and got a button to continue signup (lost the context I'm coming from)
I found these nested SSOs very confusing
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/a61c6e3d-60cb-4542-9ae1-ffda92067f16">

**Comment by syphax-bouazzouni** [comment]
Close as not reproducible
