### ISSUE TITLE
Window opened when passing on the EarthPortal logo

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#102]
![image](https://github.com/user-attachments/assets/ba64ad73-946d-470c-a366-2274950b6fa7)

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal is working on fixing that https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/851, will come soon in EcoPortal

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/pull/136
![image](https://github.com/user-attachments/assets/8c8dea7c-ef15-433a-a914-b3e852c4870b)
