### ISSUE TITLE
BiodivPortal and AgroPortal not responding

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#103]
In the Browse page, in "Results from external portals" AgroPortal and BiodivPortal are not responding
![image](https://github.com/user-attachments/assets/bf54e060-c377-43ca-b1e2-29c134d60be1)
![image](https://github.com/user-attachments/assets/8ad1f9a9-cfed-43b3-98ff-2f7499a54c3c)
![image](https://github.com/user-attachments/assets/0338a601-0cae-43ac-99a2-b7cceb102c7c)

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal how do you explain this even if the two portals APIs are not down ?  Maybe we should not block the check at all and just inform the users that the federated portal was down in the 4 last hours.

**Comment by Bilelkihal** [comment]
> @Bilelkihal how do you explain this even if the two portals APIs are not down ? Maybe we should not block the check at all and just inform the users that the federated portal was down in the 4 last hours.

Maybe this is relative to a bad configuration of these two portals, can you check this @syphax-bouazzouni 

For the idea of keeping the check and displaying only a tooltip, this will make the status feature with almost no sense. Instead I think we should investigate behind the real issue here.

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal it is not a configuration issue, as I tested it before, and worked, you can test it with https://ecoportal.lifewatchdev.eu/ontologies/?sort_by=ontology_name&portals=earthportal,agroportal,biodivportal, 
It is just that sometimes those portals are down for some seconds/minutes/hours, and as we cache it for 4 hours (I think) it stays like that even if no more is the case.

**Comment by Bilelkihal** [comment]
> @Bilelkihal it is not a configuration issue, as I tested it before, and worked, you can test it with https://ecoportal.lifewatchdev.eu/ontologies/?sort_by=ontology_name&portals=earthportal,agroportal,biodivportal, It is just that sometimes those portals are down for some seconds/minutes/hours, and as we cache it for 4 hours (I think) it stays like that even if no more is the case.

Yes your are right, they are back to work now (btw we refresh the cache each 2 hours not 4) and I don't see it a big deal if a portal was down and we see it like that for the next two hours. What do you think? 
<img width="885" alt="image" src="https://github.com/user-attachments/assets/b0fdb280-eb24-43c7-8316-bf783f6c4594">

**Comment by syphax-bouazzouni** [comment]
> > @Bilelkihal it is not a configuration issue, as I tested it before, and worked, you can test it with https://ecoportal.lifewatchdev.eu/ontologies/?sort_by=ontology_name&portals=earthportal,agroportal,biodivportal, It is just that sometimes those portals are down for some seconds/minutes/hours, and as we cache it for 4 hours (I think) it stays like that even if no more is the case.
> 
> Yes your are right, they are back to work now (btw we refresh the cache each 2 hours not 4) and I don't see it a big deal if a portal was down and we see it like that for the next two hours. What do you think?

@Bilelkihal  the issue I think is that the portals are down a lot for some seconds/minutes, and it makes it as if they were always down, so rarely usable in the federation, Maybe the solution would be to have the cache reduced to 10 minutes.

**Comment by Bilelkihal** [comment]
I'm not a big fan of this idea of 10 minutes, if a portal is down, each 10 minutes we will get that loading animation for it for 20s which is annoying, I prefer going with 1h or keeping the 2h.

**Comment by syphax-bouazzouni** [comment]
Moved the future discussion on this to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/889,  we will see how it behaves when in production after some time.
