### ISSUE TITLE
Browse page filter results (Federation)

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#104]
I am testing the federation developement (test line 40 and 41).
I've added EarthPortal semantic resources to the Browse page and the duplicated resources are merged correctly (test line 40). 
![image](https://github.com/user-attachments/assets/43e34baf-f19a-4402-8d88-6a10a54f697f)

But when i start filtering the information (in this case I have selected the category "EARTH"), the same resources are now just connected to EarthPortal.

![image](https://github.com/user-attachments/assets/ad10c808-aa50-47e8-8b71-4c2fd27e23fa)

The only difference between the EcoPortal submission and the EarthPortal one is the category (in EcoPortal ACTRIS vocabulary is not categorised as "EARTH")

**Comment by syphax-bouazzouni** [comment]
I think it is because they are not tagged in the category EARTH in EcoPortal.  So this result says that for the category EARTH, he found them only in EarthPortal.

**Comment by martinaPulieri** [comment]
We have to have the same categories then?

**Comment by syphax-bouazzouni** [comment]
> We have to have the same categories then?

If you filter by categories yes, same for the other filters I think also.

**Comment by syphax-bouazzouni** [comment]
@martinaPulieri what is your opinion on this, is there something to fix here or do we close this issue?

**Comment by jonquet** [comment]
Fyi: the harmonizaiton of categories is still ongoing and this is a topic for tomorrow meeting.

**Comment by martinaPulieri** [comment]
let's wait for the meeting to discuss this

**Comment by syphax-bouazzouni** [comment]
@jonquet @martinaPulieri what is the state of this issue? to close or is any urgent change requested to be done in this iteration?

**Comment by martinaPulieri** [comment]
@syphax-bouazzouni i think we can close for now the issue.

**Comment by jonquet** [comment]
No other comment for the moment too. I suggest we see a bit how the federation of categories goes before another cycle of feedback/updates on this.
