### ISSUE TITLE
SSO users error

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#105]
I have done the login through the SSO with a new user. I have used my personal email (tina.pulieri@gmail.com).

Log in as admin with the institutional email. In the admin panel and "Users" tab, I have tried to log in as my new account (tina.pulieri@gmail.com) and it doesn't work. See the screen recording.

https://github.com/user-attachments/assets/b3157411-a76d-48ea-92da-67faf55f5e01

If I do the same with another account created without the SSO, this isssue does not rise.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/857
