### ISSUE TITLE
SSO impossible to edit user information

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#106]
I logged in with the SSO with a new user. I wanted to edit the username, but I was redirected to the log in page each time. You can see the behaviour in the video.

https://github.com/user-attachments/assets/6b4e29ee-6e7d-4496-add3-2758e040db9e

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/857
