### ISSUE TITLE
Duplicated EcoPortal source badge

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#107]
![image](https://github.com/user-attachments/assets/823c4ed9-71f5-4ca3-bc2e-ff4d86dbd0d2)

**Comment by syphax-bouazzouni** [comment]
Fixed in #108 
![image](https://github.com/user-attachments/assets/acf648b6-adf2-409d-b807-02b2ac3dfde5)
