### ISSUE TITLE
SSO users information edited not saved

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#109]
I'm trying to edit the username. It says that the information are updated successfully but the username is still the same.

![image](https://github.com/user-attachments/assets/8d11126e-012c-419f-9c48-bc031fb73ca6)

![image](https://github.com/user-attachments/assets/2d799532-bdcb-4316-93b5-86113c3a3534)

**Comment by syphax-bouazzouni** [comment]
you can not change a user's username as it is its ID. 
@bilelkihal do you confirm this? If yes if should not make the form contain the username.

**Comment by Bilelkihal** [comment]
Yes the username is the ID,
in this case I should disable the field username in this form
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/15153d92-1a59-4e2c-99d7-83e930dd8202">

**Comment by syphax-bouazzouni** [comment]
Fixed this by two things, 

- in the UI, I removed the acronym input as you can't change it anyway 
![image](https://github.com/user-attachments/assets/00df48cc-0be0-4e15-bd3d-3d79c9888691)

- in the API, I updated the SSO user creation to not use the full email as the username but just to take the first part of the email before the `@`
 
Both deployed
