### ISSUE TITLE
SSO - login form

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#110]
For consistencies with the other LifeWatch ERIC platforms:
1. the login form should include the title "Sign in to your account" before the username and password text edit
2. update the sentence "Or connect using" with "Or sign in with"
3. remove the LifeWatch ERIC blu logo and put a button "LifeWatch ERIC" (white text and blue background)

**Comment by syphax-bouazzouni** [comment]
Fixed in 5517d8e74f3a76243cad42a3077a4bd1a10e8d5f
![image](https://github.com/user-attachments/assets/74e9cebb-5fd8-4aa9-999f-51183fde3b96)
