### ISSUE TITLE
SSO - register form

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#111]
For consistencies with the other LifeWatch ERIC platforms, the register form should have the link in the checkbox to acknowledge and accept the terms and conditions (the same of the footer).

**Comment by syphax-bouazzouni** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/f7b3cd75-5d6e-4f13-bc34-e4d6afbee950)
