### ISSUE TITLE
Top Nav Bar - VocBench

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#114]
Vocbench --> VocBench

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/6fec44fe629b43058b64c073d3f8de317fd2112b 
![image](https://github.com/user-attachments/assets/cfad3711-cabe-47b3-b545-0dfce6673e64)
