### ISSUE TITLE
Top Nav Bar - search input

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#115]
Please change the placeholkder text inside the search input text on the top nav bar simply with "Search..."

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/894c41f9345c7cdb81dd57b8e694693fd9cd3e70
![image](https://github.com/user-attachments/assets/d6979ba2-8dfc-4d5b-9830-9c245d8a73fb)
