### ISSUE TITLE
Top Nav Bar - Login button

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#116]
Since the login button is on a header with blue background, could you please change the button in order to make it more visible for the user?
White background and blue text.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/19e072b2ec7be3b028daa60f7df4d55b99567f74
![image](https://github.com/user-attachments/assets/da34e25c-ebe6-49c1-acb7-a23c4db7eb77)
