### ISSUE TITLE
Feedback - missing URL + captcha

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#117]
In the feedback form there is no link for the Github issues.

Moreover, is the captcha included?

**Comment by syphax-bouazzouni** [comment]
The recaptcha is enabled only in production

**Comment by syphax-bouazzouni** [comment]
Hello @luciaV86, 
For the ReCaptcha to be enabled I will need the following credentials `site_key` and `secret_key`, you can send it to by email to me.


@bilelkihal This does not work also in AgroPortal can you check it https://agroportal.lirmm.fr/feedback ?

**Comment by syphax-bouazzouni** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/bccce8aa-4fe5-40bb-9b67-21b69f80e2fd)
