### ISSUE TITLE
General - primary color

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#118]
The correct value of the primary color is #0f4e8b and not #0f4e8a (the last character is wrong).
It is valid for both backgorund and blue text.

**Comment by syphax-bouazzouni** [comment]
I think it is done now,  in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/751cf7d3a2aeec07ca4aa9902948073c4aabfecc
![image](https://github.com/user-attachments/assets/d3404f8e-80c8-4189-b33c-e6054e61ee20)
@luciaV86 please can you check again, and close this issue, if is the correct color you wanted.
