### ISSUE TITLE
Home page - statistics - EcoPortal in figures

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#119]
The statistics page should be improved as follows:

1. the last 11 years is something static? We have EcoPortal since 2020 so it is not correct to show values before that period.
2. the table can be more readable by inserting pagination instead of having a very long version
3. why there are already vaues for the next month?
4. is the time period updated automatically or do we need to do it manually via code or similar?

**Comment by syphax-bouazzouni** [comment]
Moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/886 for future iterations
