### ISSUE TITLE
Recommender page - buttons not working

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#120]
The buttons at the end of the recommender page are not working. In particular:

1. JSON opens a new tab but with an error
2. Cite does not answer

**Comment by syphax-bouazzouni** [comment]
Fixed for cite us ma didn't get any error with the JSON button. 
![image](https://github.com/user-attachments/assets/7da55b70-8b0d-4119-b5b7-3d356b1c4bac)
