### ISSUE TITLE
Footer - team page

### ISSUE THREAD

**Issue by luciaV86** [lifewatch-eric/ecoportal_web_ui#122]
This page needs the following improvements:

1. move Nicola Fiore in the past team section
2. remove the email of the past members
3. fix the images' resolution

**Comment by martinaPulieri** [comment]
Add to Davide Raho the Organisation (the same as Ilaria): Research Institute on Terrestrial Ecosystems - National Research Council

**Comment by syphax-bouazzouni** [comment]
Fixed in 8f50632c834c3784497fd40bfee90cab5bad8d30
![image](https://github.com/user-attachments/assets/4ecfecf1-e214-41a8-86b3-a5d829781d8f)
