### ISSUE TITLE
Reset password - email change

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#125]
When resetting the password, the email should be arriving from semantics@lifewatch.eu

![image](https://github.com/user-attachments/assets/ec1fdf2a-d3ed-4f35-9aa3-749d67132894)

**Comment by syphax-bouazzouni** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/b3ce4b79-4ef3-4275-92dd-214c4726ee1b)
