### ISSUE TITLE
Categories name

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#126]
Can categories names be shown not with their acronym but with their pref Label?
![image](https://github.com/user-attachments/assets/bce20cb8-4bf8-4486-bb34-f39940ee8b91)

**Comment by syphax-bouazzouni** [comment]
Ping @jonquet and @Bilelkihal, for opinions on this.

**Comment by jonquet** [comment]
Not really. Doesn't fit in here if we put the name. Although I recognize the situation is not ideal, the proposition was to go with this approach for the moment and focus on the federated categories before changing this UI.

**Comment by martinaPulieri** [comment]
@jonquet what do you mean by saying it "doesn't fit"? Is a text problem? 

In any case, it clashes a lit bit with the general layout of the categories.

**Comment by Bilelkihal** [comment]
> @jonquet what do you mean by saying it "doesn't fit"? Is a text problem?
> 
> In any case, it clashes a lit bit with the general layout of the categories.

@martinaPulieri 
This is how categories are going to look like using their names instead of acronyms
![image](https://github.com/user-attachments/assets/61c6b794-049e-45ee-85bd-7b63cb45f3bc)

**Comment by jonquet** [comment]
INdeed, its looks not bad for the old AgroPortal categories. 
@Bilelkihal Could you make a similar screenshot from SatgePortal with federation so we cans see how it looks with new categoriy names ?

**Comment by syphax-bouazzouni** [comment]
Moved the proposition to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/885
