### ISSUE TITLE
Homepage - bubbles and visit page

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#128]
When clicking on the 3 dots bubble an error page pops up.

![image](https://github.com/user-attachments/assets/5729cce6-94e0-4543-a089-6232b6efb040)

**Comment by syphax-bouazzouni** [comment]
Fixed in cf0893ea22530095992670adba0c7ba44d9eddab
![image](https://github.com/user-attachments/assets/d2919da1-e364-456e-bbbc-84e65a375b8a)
