### ISSUE TITLE
O'FAIRe tool "Go to API" button doesn't work.

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#129]
The "Go to API" button is not working for FAIR Score evaluator service in the homepage. The page remains in loading.

![image](https://github.com/user-attachments/assets/f7e5c204-e76a-42a6-8626-97e18745eb24)

**Comment by syphax-bouazzouni** [comment]
@luciaV86 can you open for public the port 8082, to make this work.

**Comment by luciaV86** [comment]
Done, for both DEV and new PROD

**Comment by syphax-bouazzouni** [comment]
Thanks @luciaV86,
@martinaPulieri this should work now, I let you open this issue  again if it is not the case.
