### ISSUE TITLE
Issues with properties

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#130]
Important, Parham: OWL 2 introduced several vocabularies to provide a more explicit hierarchy for declaring and organizing properties. Specifically, owl:topObjectProperty and owl:topDataProperty are embedded in Protégé, and it is common practice to define all properties as sub-property-of one of these two. In EcoPortal, when properties are declared in this way, they do not appear in the [Properties tab](https://ecoportal.lifewatchdev.eu/ontologies/SPO?p=properties). After removing the annotations to owl:topObjectProperty and owl:topDataProperty for several properties, these specific properties reappeared in [the relevant tab](https://ecoportal.lifewatchdev.eu/ontologies/SPOT7?p=properties).

**Comment by jonquet** [comment]
This issue is interesting.
Can you precise what you mean exactly by "removing the annotations to owl:topObjectProperty and owl:topDataProperty for several properties" ? 

Do you have examples of the 2 situations?

**Comment by Ramezani-07** [comment]
Example with these annotations: 

@prefix : <https://kos.lifewatch.eu/ontologies/lw/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:characteristics rdf:type owl:ObjectProperty ;
                 _**rdfs:subPropertyOf owl:topObjectProperty ;**_
                 rdfs:domain :ObservationCollection ;
                 rdfs:range :ObservableProperty ;
                 rdfs:isDefinedBy "https://kos.lifewatch.eu/ontologies/lw/"^^xsd:anyURI ;
                 rdfs:label "characteristics" ;
                 owl:versionInfo "1.0.0" .
                 
:catalogNumber rdf:type owl:DatatypeProperty ;
               _**rdfs:subPropertyOf owl:topDataProperty ;**_
               rdfs:domain :Observation ;
               rdfs:comment "An identifier (preferably unique) for the record within the data set or collection." ;
               rdfs:label "catalog number" .
               
               
Example without these annotations: 

:characteristics rdf:type owl:ObjectProperty ;
                 rdfs:domain :ObservationCollection ;
                 rdfs:range :ObservableProperty ;
                 rdfs:isDefinedBy "https://kos.lifewatch.eu/ontologies/lw/"^^xsd:anyURI ;
                 rdfs:label "characteristics" ;
                 owl:versionInfo "1.0.0" .
                 
:catalogNumber rdf:type owl:DatatypeProperty ;
               rdfs:domain :Observation ;
               rdfs:comment "An identifier (preferably unique) for the record within the data set or collection." ;
               rdfs:label "catalog number" .

**Comment by syphax-bouazzouni** [comment]
I moved this feedback to https://github.com/agroportal/project-management/issues/638, you can follow the discussion there, as it is not urgent for the current iteration.
