### ISSUE TITLE
Instance page - Raw data section

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#131]
In Raw data section of the instance page, at least the "owl:NamedIndividual, "rdfs:label" and "rdfs:comment" should be visible.

**Comment by jonquet** [comment]
Can you precise this one.

**Comment by Ramezani-07** [comment]
Look at the following example:
<https://www.lifewatchitaly.eu/resources/Observation-10f03cdd-8274-482f-88d8> a owl:NamedIndividual,
    lw:Observation ;
    rdfs:label "10f03cdd-8274-482f-88d8" ;
    rdfs:comment "It's a test instance of class lw:Observation" ;
    lw:catalogNumber "1577" ;
    lw:dateTime "18/10/07" ;
    lw:eventId "b".
    
We usually annotate an instance of a class with owl:NamedIndividual, rdfs:label and rdfs:comment. Within a test on Ecoporta, I see the label, type and comment of the instance are visible. So I think we can close this issue.

**Comment by jonquet** [comment]
@Ramezani-07 Can you give me the pointer to the correpsonding EcoPortal page so I can see the term and how it displays in EcoPortal?

**Comment by syphax-bouazzouni** [comment]
> We usually annotate an instance of a class with owl:NamedIndividual, rdfs:label and rdfs:comment. Within a test on Ecoporta, I see the label, type and comment of the instance are visible. So I think we can close this issue.

Close as seems to be satisfied.
