### ISSUE TITLE
EcoPortal does not find persons that are present in the database

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#132]
I was trying to add several persons already present in the EcoPortal agent database, 
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/b3054563-99fc-4052-bb97-6c52c394f941">
but the menu was empty
<img width="787" alt="image" src="https://github.com/user-attachments/assets/50f8787f-3565-46b2-8ace-c4b538208046">

**Comment by syphax-bouazzouni** [comment]
@bilelkihal did this work in AgropPortal, I mean create a new agent and then try to search it and find it. Normally each time you create an agent and save it, it indexes it automatically.

**Comment by martinaPulieri** [comment]
Sorry, now it works. I don't know what was the issue.
