### ISSUE TITLE
Error in EcoPortal URL

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#134]
when adding EcoPortal as a catalogue, it shows the wrong URL. It should be https://ecoportal.lifewatch.eu.
![image](https://github.com/user-attachments/assets/8dfedaf4-7514-4667-b360-c70be7e7e2e2)

**Comment by syphax-bouazzouni** [comment]
Fixed 
![image](https://github.com/user-attachments/assets/27aa8476-a45a-4074-88a4-c6a396697304)
