### ISSUE TITLE
Wrong counting in the statistics

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#137]
The counting of the semantic resources in the statistics is wrong. 

![image](https://github.com/user-attachments/assets/2965b802-fadd-4aac-a1d5-ead7bbbdc40c)

![image](https://github.com/user-attachments/assets/84f4e775-8bb3-435f-ae29-a52eab9ab1bf)

**Comment by syphax-bouazzouni** [comment]
FIxed 
![image](https://github.com/user-attachments/assets/8d85208c-8b22-42c0-b456-5273977d3ace)
