### ISSUE TITLE
Bioportal "text" and link instead of Ecoportal in the  email notification 

### ISSUE THREAD

**Issue by Davrah** [lifewatch-eric/ecoportal_web_ui#139]
object: **[Bioportal]** The Interpretation Ontology Parsing Success

Email body: The Interpretation Ontology (INTERPRETATION) was processed for use in **Bioportal.** Here are the results:
The ontology can be **[browsed in Bioportal](http://ecoportal.lifewatchdev.eu/ontologies/INTERPRETATION?invalidate_cache=true).**

Thank you,
The **Bioportal** Team

**Comment by syphax-bouazzouni** [comment]
Fixed, to see if it did work, next time we have a email
