### ISSUE TITLE
TAB "Metadata Administration" duplicated

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#22]
![Senza titolo](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/3f5373a0-bc7d-4c3c-a867-decec3192664)

**Comment by syphax-bouazzouni** [comment]
fixed in #28 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/e61ee815-37e7-4116-acde-4c6406072973)
