### ISSUE TITLE
Empty table in popup

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#23]
In Administration Console -> Ontology Administration, when the user click "Submissions" the table in the popup is empty:

<img width="1139" alt="Screenshot 2023-09-19 alle 14 49 19" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/034e9bbd-9236-4c3f-8bb2-54b0733a7799">

**Comment by syphax-bouazzouni** [comment]
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/2474713c-d8e0-4707-af64-5fd9e4065fd8)
Fixed
