### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#24]
The link to dublincore should be removed. It is broken (404)

<img width="1055" alt="Screenshot 2023-09-19 alle 14 54 27" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/3b820f5f-46a3-4450-b1f9-a3738a733fae">

**Comment by syphax-bouazzouni** [comment]
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/515cb672-62ce-4071-a2c7-9f4bc43c80fc)
Fixed

**Comment by jonquet** [comment]
The relevant link is now: https://nkos.dublincore.org/nkos-type.html

The idea was to provide a link to an external reosurce describing what are the KOS type sugegsted by the popup. 
I recommend to keep the link somehere (especially in the new metadata edition pages coming up)
