### ISSUE TITLE
Green buttons

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#26]
In "Administration Console -> Metadata Administration" the "Get values" button is green instead of blue

![image_2023_09_28T16_03_56_639Z](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/2b0e3c13-9ccc-427f-a4b5-34e1a615acb9)

**Comment by syphax-bouazzouni** [comment]
Fixed  in #28 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/4bcf2893-d245-41d2-8732-bf5879c22eeb)
