### ISSUE TITLE
FAIRness assessment - A1Q1 wrong evaluation

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#27]
Even if the criteria is fulfilled, the score is 0 instead of 6.

![image_2023_09_28T16_07_11_071Z](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/55112968-4759-487d-b27c-a97b55bb30ba)

**Comment by jonquet** [comment]
Seems the dct:identifier property is not well encoded. As it contains an array instead of simply a DOI URL. 
This might come form the migration btw the 2 versions. 

@gturrisi-lifewatch  Can you edit the metadata record of this vocabualry and check again.

**Comment by syphax-bouazzouni** [comment]
> Seems the dct:identifier property is not well encoded. As it contains an array instead of simply a DOI URL. This might come form the migration btw the 2 versions.
> 
> @gturrisi-lifewatch Can you edit the metadata record of this vocabualry and check again.

In the new model; `identifier` attribute is an array, you can check here https://data.stageportal.lirmm.fr/submission_metadata, 


The A1Q1 tests if those URLs are resolvable, i.e we can they are accessible and returning 200 or 302 (a redirection) status.

But maybe the test of reasonability does not works, as we can the same error in Stageportal
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/b1eadb56-44f9-4ace-9c99-d991d4c2dc83)

**Comment by syphax-bouazzouni** [comment]
This one is a more complex issue, that will take some time to resolve. The issue was raised to Agroportal https://github.com/agroportal/fairness/issues/33 and will be when we will do a new  iteration over O'FAIRE for a new release

**Comment by syphax-bouazzouni** [comment]
fixed 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/bfc71108-b297-4669-b916-d0cbe7adc7b0)
