### ISSUE TITLE
Impossible to add a new Catalog where the ontology is uploaded

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#32]
When entering the information in which Catalog the ontology is uploaded I get this:
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/b1b29296-3641-4716-b3e5-0a1465a2660a)
But I actually cannot change the entries as it is a drop-down list:
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/06b9ecb9-bf8c-48b0-869e-daa6c4cd44a6)
So I wonder how I could fix this?
Also: this information is already in the file.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/bd6134a4-4e15-4f8a-b6f5-1252f4518b2b)

So why isn't it recognized by the portal and automatically used?

**Comment by syphax-bouazzouni** [comment]
In which ontology is this? or is it for all?

**Comment by gturrisi-lifewatch** [comment]
The user reported: `"it is at the moment only a problem with EnvThes"`

**Comment by syphax-bouazzouni** [comment]
It seems to work in the new Ecoportal version, 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/53359a99-8248-4b60-956f-e0b2cb4d4b61)
