### ISSUE TITLE
Inconsistencies between old and new versions on the number of classes, concepts, instances and notes

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#33]
**Old EcoPortal** https://193.204.79.111:
![Screenshot 2023-11-07 alle 09 31 08](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/885f99b0-e856-48f3-b7ba-8dd968268c28)

**Current EcoPortal** https://ecoportal.lifewatch.eu:
![Screenshot 2023-11-07 alle 09 31 03](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/c60b9582-0676-451b-9443-2a7027fae886)

**Comment by syphax-bouazzouni** [comment]
This is due I think, because the metrics were not calculated 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/d63e3e1a-6d53-41da-879e-68f4c8160fd1)
Try this cmd, 
```
cd /srv/ontoportal/ncbo_cron/
bin/ncbo_ontology_process -a -t run_metrics 

```
it will generate the missing metrics

**Comment by gturrisi-lifewatch** [comment]
Thanks, I did the `bin/ncbo_ontology_process -a -t run_metrics`  command as `ontoportal` user and then flushed all the caches.
Now the metrics appears.
Thanks!
