### ISSUE TITLE
O'FAIR service

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#34]
@syphax-bouazzouni 

The O'FAIR service is not working again.
when the service has problems, the navigation of the entire EcoPortal platform is very slow.

**Comment by syphax-bouazzouni** [comment]
Solved in #35  by doing a fast timeout. So if the service is down the UI will wait maximum 1s, before going on.

But the real subject is whether the OFAIRE service is going down that much, if yes? What would be the cause? Can save  logs and share with me here the logs, next time O'FAIRE is down

**Comment by syphax-bouazzouni** [comment]
Hi @gturrisi-lifewatch, do you think this issue is fixed ? and we can close this?

**Comment by gturrisi-lifewatch** [comment]
It seems that the problem is no longer occurring. I close as fixed, thanks.
