### ISSUE TITLE
Green buttons and wrong wizard title

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#36]
We found green buttons in these wizards:
- Add a new comment
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/edce319d-013f-4766-b87a-ae3808ae0b6e)

- Add proposal
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/58788574-7f1d-4a1a-bb52-c5bc9547b1d2)

- Create new mapping
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/f0bd8b5a-391f-4438-836e-2b5bb88dc96d)

In this last one, the title should be "Create a new mapping for ecological domain"

**Comment by syphax-bouazzouni** [comment]
Fixed  
* Add a new comment
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/390d9c93-56e4-4752-851b-45083e3044fe)

* Add proposal
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/25b3f075-752d-4f21-8860-b21b4876e07a)

* Create a new mapping
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/3db71a15-c011-4eed-a682-6c45f0276d0e)
