### ISSUE TITLE
FAIR assessment - F2Q2 wrong evaluation

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#37]
omv:numberOfClasses, omv:numberOfProperties, omv:numberOfAxioms, omv:numberOfIndividuals are not detected by the system

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/84874086-a882-4874-bb70-3bfcae05dc57)

even if the displayed metrics are these

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/74e6a686-ee9e-4c80-968b-e485bc707739)

**Comment by syphax-bouazzouni** [comment]
fixed 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/67858891-61b8-48a3-b213-c95c236f8bb7)
