### ISSUE TITLE
SMTP connection fails from "Forgot Password"

### ISSUE THREAD

**Issue by gturrisi-lifewatch** [lifewatch-eric/ecoportal_web_ui#38]
The authentication to SMTP server is not working when the user requests the reset of his password.
Is it possible to disable the _"Forgot password"_ link and put instead a label with the following text?

**"If you forgot your password, please send an email to semantics@lifewatch.eu"**

<img width="476" alt="Screenshot 2024-01-25 alle 10 59 12" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/117273860/f0f7c717-0fec-4353-998c-3f7717abafcc">

**Comment by syphax-bouazzouni** [comment]
Fixed in the new Ecoportal version
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/da19d5ec-6341-446e-8859-c0b405ba590c)
