### ISSUE TITLE
"Show retired semantic resources" button not working properly

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#47]
When enabling the "Show retired semantic resources" the system should show just the retired resources, and in our case should be an empty page since there are no retired resources, but instead it shows all the semantic resources.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/8bf9bf30-36a1-4cbb-b450-da5dc1e8d3e3)

**Comment by syphax-bouazzouni** [comment]
hello @martinaPulieri , in this case, the switch "Show retired semantic resources", does not show only the retired.

by default we show the not retired/deprecated, and when enabled we show the retired in addition.

**Comment by martinaPulieri** [comment]
Okay so it's an addition to the one already showed?

**Comment by syphax-bouazzouni** [comment]
Yes, the same for the "Show semantic resource views" above it

**Comment by martinaPulieri** [comment]
Got it. Thanks for the clarification

**Comment by jonquet** [comment]
Adding a small technical justification : its some kind of a reverse query (not displaying all the ones that are false) which makes it a bit more cumbersome to implement. When we revise the Browse page last year we decided to left that aside.

**Comment by martinaPulieri** [comment]
@jonquet @syphax-bouazzouni could be useful to change the label of the button? In order to make it more understandable?

**Comment by jonquet** [comment]
Indeed.. this was already discussed and acted in AgroPortal ... and lost/forgotten ;)
<img width="288" alt="Capture d’écran 2024-06-06 à 14 39 26" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/7379183/ceaa26a0-c07b-4d1e-b372-d68193df6e38">

We need to remove the  "only"
