### ISSUE TITLE
Error 404: Homepage annotator not working

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#49]
The annotator from the homepage gives the 404 error page

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/58f0b5c4-e033-4099-b072-70b2e3346108)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/391ca70997e38306f6d95c2e386b4075285366c3
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/ae5969e8-9b9e-4c43-9510-637c2b662aeb)

**Comment by martinaPulieri** [comment]
I still have the same issue

**Comment by syphax-bouazzouni** [comment]
Sorry, I did not deploy the fix, now done (http://ecoportal.lifewatchdev.eu/annotator?text=Invasive+alien+species+are+plants,+animals,+pathogens+and+other+organisms+that+are+non-native+to+an+ecosystem,+and+which+may+cause+economic+or+environmental+harm+or+adversely+affect+human+health)
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/de1ccf8f-8156-4aa1-bc55-c8cad53572f3)
