### ISSUE TITLE
0 Semantic Resources

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#50]
The section "EcoPortal in figures" shows always 0 semantic resources published

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/8962cf04-d847-482a-ab2f-1aaf4233b831)

**Comment by syphax-bouazzouni** [comment]
same as https://github.com/lifewatch-eric/ecoportal_web_ui/issues/58
