### ISSUE TITLE
404 error for the "See details" page 

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#51]
When clicking on the "See details" for the section "EcoPortal in figures" the 404 pops out.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/ab62071f-f75c-438a-a3e9-8a2035e9cfb4)

**Comment by syphax-bouazzouni** [comment]
the button "See details" was removed (https://github.com/lifewatch-eric/ecoportal_web_ui/commit/5c1184530fd57ee99a0772ea3e5542224e5d24cf), as it works only if Google Analytics enabled. When enabled that button will be back automatically. 

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/19214e8f-3e99-4299-9d78-cde1a74aed83)
