### ISSUE TITLE
wrong label

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#53]
Instead of "ontologies" here it should be "semantic resources"

<img width="195" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/fa8ca474-6269-445e-b6b9-8629676d9669">

**Comment by jonquet** [comment]
@syphax-bouazzouni will explain and certainly setup how we made the word "ontology" a variable that can be changed everywhere on the web UI automatically to another expression eg semantic resource

**Comment by syphax-bouazzouni** [comment]
fixed  in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/fdcfa5ca80a64a2f93df5ba61b9a8639868f9c2a
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/cf4cec9f-a783-4469-995c-fcbef4db7b60)
