### ISSUE TITLE
Not clear search box

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#54]
I think there is should be some hints of what to search: e.g. "Search for semantic resources" because it is not quite clear. I was searching for mapped concepts, not for semantic resources.

<img width="1164" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/87914bf3-0d38-412e-b6ca-aa2dbdd6a30d">

**Comment by jonquet** [comment]
This is for @Bilelkihal. 
Indeed we usually put a "default" place holder message or exmaple in the form

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/ee7fcaecd71b5b534875eb00ec5d3ec586f67d72
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/89b1f7f5-0552-433a-b8b0-230a0f411791)
