### ISSUE TITLE
Empty Mappings wizard

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#55]
<img width="1149" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/3c4b8be0-7aea-4ad0-8750-a457d26282b3">

When browsing for the mapped concepts in the "Mapping" tab of the semantic resource and clicking on a concept, the resulting wizard (which should show the details about the concept?) is empty.

<img width="1167" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/832fbe4b-5bcb-4240-8a81-f449e1714f29">

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/2d4e22e14bb23f20a16fb36901482ef74f1f0093, now clicking on the concept name, opens a new tab with the concept details.
