### ISSUE TITLE
SKOS collections filter proposition

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#56]
I see what you are doing here with the filters by collections, but is not intuitive. 
If it is a filters it has to act as a filter, and show just the concepts in the selected collection. In this way, since most of the concepts member of collections are inside the hierarchical tree, users are not able to see the collection members' directly, but they have to browse the tree.

<img width="1198" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/d8d3aa99-bbae-41c3-bd76-2b0fed1ff8a4">

**Comment by jonquet** [comment]
Humm this is an interesting remark... I can understand it. 
This will be ok to avoid dispalying the siblings that are not in a collection.. but @martinaPulieri how would you do for concepts that are not in the collection but do concept narrower concepts that are inside the collection ? 
In other words we need to display them too to enable the possibility to pen them. 

Still it could be an interesting alternative approach (maybe to include in the mutilple tree view parameters discussed with @ Bilelkihal) would be do decide to display the concept that are not explicitly in the collection only if they have children or maybe (harder to implement!) if they have descendants that are in the collection.

**Comment by martinaPulieri** [comment]
@jonquet I would display the concepts that are not explicitly in the collection only if they have children belonging to it (keeping the the coloured dot in this case is useful), and I would "remove" all the other concepts that do not belong to that collection.

**Comment by jonquet** [comment]
"only if they have children belonging" you mean direct children or all descendants... ? 
Its not the same as in one case we need to "open" only the children of the current level then display them at the current level only if they have direct children in the collection 
where as descendants means the same behaviour recursively, whcih is technically impossible as it would mean the UI traverse each time all the hierachy down to each leaves for all the roots ... basically this is why we are trying to avoid (for time response and scalability purpose) with a tree build step by step.

**Comment by martinaPulieri** [comment]
To practically show you what I mean.

<img width="1250" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/860c5999-9fa7-4ee8-a4cc-c8f0534320d3">

Then the tree view can be closed. Is not a problem.

**Comment by jonquet** [comment]
OK will discuss this with the team to see what to do.

**Comment by syphax-bouazzouni** [comment]
Moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/680
