### ISSUE TITLE
Date of original creation - 6 digits for the year

### ISSUE THREAD

**Issue by dadeex** [lifewatch-eric/ecoportal_web_ui#57]
It is possible to enter 6 digits for the year

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/5df098dd-76d5-4be0-9667-d9f32985d883)

**Comment by syphax-bouazzouni** [comment]
Moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/686 for further investigation, as I did not find any easy solution to solve this as we use an external component to handle that.
