### ISSUE TITLE
0 semantic resources

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#58]
In "EcoPortal in figures" in the homepage, the counter for the semantic resources is at 0.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/878dfef6-0245-4ef0-a83b-d24c6a2b00c8)

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/5c1184530fd57ee99a0772ea3e5542224e5d24cf
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/2791660a-2ff4-4ec0-a307-ac6b4e68f497)
