### ISSUE TITLE
Surname's in lower cases

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#59]
As shown in the screenshot, the surname of the contact is in lower case.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/80ba1208-ef9d-4ecb-8b94-b5430f93a7e0)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/e6403eda3c0f797184348c688d3619acb2c50fc8
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/7eecbcb7-1bf0-4d47-9b73-cb8f0ade4078)
