### ISSUE TITLE
Add CNR logo in Support & Collaborations

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#60]
Is it possible to add the CNR logo in the Support & Collaborations section in the homepage?

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/2bbfdcc0-3161-440e-a6d2-d91be8f6fc59)

**Comment by syphax-bouazzouni** [comment]
Done 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/88bd4f9c-694a-4e44-a155-e41c6a5f91f4)
