### ISSUE TITLE
Cookie banner

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#61]
It is important to add the cookie banner and it has to have the content and the form of LifeWatch ERIC. 

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/d9d47a27-5e17-4c82-a981-d81ffceb108d)

You can see how it is done in the LifeWatch ERIC webpage (lifewatch.eu) or on the help desk (helpdesk.lifewatch.eu).

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri, I can do only the Accept and Deny buttons, "View preferences" is harder as we don't have any way currently to filter cockies by functionalities.

Is it okif we have only the "Accept" and "Deny" buttons?

**Comment by martinaPulieri** [comment]
It's okay, you can keep just those two buttons. But now you have to add the direct link to the Privacy Policy and the text have to be change in this way:


We use cookies to help you navigate efficiently and perform certain functions. You will find detailed information about all cookies under each consent category below.

We also use third-party cookies that help us analyse how you use this website, store your preferences, and provide the content that is relevant to you. These cookies will only be stored in your browser with your prior consent.

Please note that disabling such cookies may affect your browsing experience.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/6d8740ac79ca9b99a87cff1ffe19b7e58bdf4795
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/e0723370-01f4-46fd-898e-5c7b9198c889)
