### ISSUE TITLE
Email icon not working

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#63]
The email icon that is in the footer leads to a 404 error page

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/d9364799-4439-403f-ba24-b800add1e599)

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/130d5d74-f11a-4347-bd7b-d63df18a0416)

**Comment by syphax-bouazzouni** [comment]
Fixed, now it opens your email client with the correct email. 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/ad4ccd06-a5f7-4764-b7c8-06b43291369b)
