### ISSUE TITLE
Twitter icon

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#64]
Update the Twitter (now X) icon in the footer

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/1f7278ae-a423-48cf-ac5e-4f9709c5398b)

**Comment by syphax-bouazzouni** [comment]
Done 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/1f28269d-e9e3-4c02-9aa9-955213283f35)
