### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#65]
For the Team page, it should be splitted in two: Team and Past team (everything in the same page).
In the Team you can leave Ilaria, Nicola, and Lucia, and add me (Martina Pulieri), Parham Ramezani and Davide Raho.

In the Past Team you have to put Giuseppe, Pierfrancesco and Xeni Kechagioglou.

As an example on how to divide the page you can see this https://sredlist.eu/#/team

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/e0d83385d148d97bc0a474596458fda77bafb38e
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/f8a8a166-efed-42c0-b1ab-7c99e109862c)


@martinaPulieri  I will need a link to where to find  Parham and Davide's profile photos and position information. I can also update the information of the others if obsolete.

**Comment by martinaPulieri** [comment]
These are the information to update. The emails are fine. I will send you by email the photos.

Martina Pulieri
Research assistant - LifeWatch Italy
University of Salento


Parham Ramezani
LifeWatch ERIC Ontology Developer


Davide Raho
Data scientist - LifeWatch Italy

**Comment by syphax-bouazzouni** [comment]
I updated in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/6b0a9a2d2077f07e635567a1551405761146dbd7,  the team page with the new information and profile pictures https://ecoportal.lifewatchdev.eu/team
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/bde40c1e-fca6-4ef8-9563-e77dd42976a3">
