### ISSUE TITLE
The semantic resource processing failed, with the current statuses: (Uploaded, Error Rdf)

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#67]
We were trying to upload a new resource (https://ecoportal.lifewatchdev.eu/ontologies/ETS_T2), but this error came up. 

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/b683f529-c72c-45ee-990d-055878c93830)

We tried to upload it with a pull URL (https://data.biodivportal.gfbio.org/ontologies/ETS/download), and also with the owl file, but we had the same error.

As I was mentioning in the first meeting, we are not capable of understanding the issue behind it.

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri , it seems to work now, did you change something? 
<img width="1313" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/88d03531-e5cd-4d82-841b-166561757b43">

Generally `Error RDF` status means the file has a syntax error.  Right now we don't have an easy way for admin/users to check the syntax error, except going to the parsing logs on the admin page.

**Comment by martinaPulieri** [comment]
No, I didn't touch anything. But the tab classes is empty.

**Comment by dadeex** [comment]
Also for new processed sources the issue remains
<img width="1210" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/58e2d9ea-b05c-49eb-ab25-aa744cfaf3b5">

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri, the issue with ETS_T2 was in the type of the resource it was set to OBO; but changing it to OWL format, made it work. (https://ecoportal.lifewatchdev.eu/ontologies/ETS_T2?p=classes) 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/59b38c02-ff84-4f2b-afb7-793afab5588c)




> Also for new processed sources the issue remains <img alt="image" width="1210" src="https://private-user-images.githubusercontent.com/59953068/344628147-58e2d9ea-b05c-49eb-ab25-aa744cfaf3b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzA0MTcsIm5iZiI6MTcxOTk3MDExNywicGF0aCI6Ii81OTk1MzA2OC8zNDQ2MjgxNDctNThlMmQ5ZWEtYjA1Yy00OWViLWFiMjUtYWE3NDRjZmFmM2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTFkZTQ1MmIwOWMwZTQyMjViNjMzMTFjMzBkOTk3MDM3MGJiNTU0YmFmZjQ3YWQ3MGE0MzM0MDY5YjhlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.42XzXuxjBjJnR1GfaQ5RK5iz6GslBoA7Q3YnKBnMk6A">

Hello @dadeex, it is not the same cause, the issue with INRAETHES is the URI metadata of that ontology was not correct, so changing from https://www.davide.davide/inrae to the correct one http://opendata.inrae.fr/thesaurusINRAE/thesaurusINRAE, fixed that ontology https://ecoportal.lifewatchdev.eu/ontologies/INRAETHESTEST3?p=classes. 

Having a wrong URI, makes it try to show all the concepts, not only the main ones. Showing all the concepts takes too much time, which explains the infinite load.
 
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/5720a36c-8c78-42f6-9285-7cb05e0ae855)
