### ISSUE TITLE
No class/concept found

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#68]
This resource has an issue with retrieving classes/concepts.

https://ecoportal.lifewatchdev.eu/ontologies/ACFORMAT?p=classes

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/f4a3087b-4520-4227-a4fd-1e40eedc23c9)

**Comment by jonquet** [comment]
This source file does not contain any skos:Concept. 
This is not a thesaurus in fact, it does not use any of the SKOS constructs. 
Its a palin RDF file. 
OntoPortal cannot handle these kind of resources. 
The minimal requirements for OntoPortal resource to be parsed is to be a SKOS thesuarus  or a OWL/OBO ontologies

**Comment by martinaPulieri** [comment]
Okay, got it. 
Thank you
