### ISSUE TITLE
missing status: ANNOTATOR

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#69]
In the Admin menu, and Semantic resources administration, all the resources have as missing status ANNOTATOR. What does it mean?

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/33ffc849-4abe-4f8a-99de-ada990e9e5dc)

**Comment by jonquet** [comment]
Means that the Annotator service tested with the content of the right side column did not work after the parsing of the resource. Those expression on the right side are taken randomly. 
The problem may come form an error during the creation of the Annotaor cache. Check the log.
