### ISSUE TITLE
Home page text

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#70]
It should be "a semantic resource"

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/d8889f02-fec5-44ad-82ae-476f143ea600)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/7de4bc90acb3ca473ea66bcf1678f0903d1ae182 all the references of "an semantic"
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/36663a63-1a6e-41f3-9225-f5085318a2b1)
