### ISSUE TITLE
RDF/XML metadata export

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#71]
We are missing the RDF/XML format export of the metadata. How so?

**Comment by syphax-bouazzouni** [comment]
Do you mean this?
<img width="875" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/4cd28541-589e-4910-8a57-b6cb6c24f525">

you can find it by clicking this link 
<img width="875" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/332a22e0-c8ed-4228-b795-2294f7dfe874">

**Comment by syphax-bouazzouni** [comment]
For Datacite, we don't have XML, because it was not implemented before
<img width="311" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/345fbef2-971f-498d-8b67-a5326be774a6">

And will be complicated to implement, in the remaining days.

**Comment by martinaPulieri** [comment]
Okay, no I didn't see that the XML was actually the RDF/XML one. Is it possibile to change the label of the XML tab into RDF/XML?

**Comment by syphax-bouazzouni** [comment]
> Okay, no I didn't see that the XML was actually the RDF/XML one. Is it possibile to change the label of the XML tab into RDF/XML?

Yes  you are right, it is better to call it "RDF/XML", done in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/c1b00f4c551c8ca069bc163099823425f634bba5
![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/29259906/9d0f69ad-5f01-4ba6-8e14-74a41ffe17b4)
