### ISSUE TITLE
Submission of new semantic resource - Mandatory fields 

### ISSUE THREAD

**Issue by dadeex** [lifewatch-eric/ecoportal_web_ui#72]
During the submission process of a new semantic resource, it is not easy to determine which fields are required and which are optional.

**Comment by syphax-bouazzouni** [comment]
They are all required in the submission process. While categories and groups are not technically required, we advise always filling them in.

**Comment by martinaPulieri** [comment]
It's best to mark every field in the first submission form as mandatory with an asterisk.

**Comment by syphax-bouazzouni** [comment]
Done in #108 
![image](https://github.com/user-attachments/assets/6faa12c2-8871-484a-8ec9-e58c2024065a)
