### ISSUE TITLE
STATUS 400  in field "status" of the semantic submission form

### ISSUE THREAD

**Issue by dadeex** [lifewatch-eric/ecoportal_web_ui#74]
After the fulfillment check of the fields of the semantic submission form, if something required was not filled, a  "400" appears in status field
<img width="572" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/afa54430-c707-4e5a-835c-ba2e6b7d3952">

**Comment by syphax-bouazzouni** [comment]
fixed in  https://github.com/lifewatch-eric/ecoportal_web_ui/commit/d5a8397615dabd4b57a7350cd707cde47fde2711 by https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/625
