### ISSUE TITLE
Semantic Submission form - single page fulfillment check

### ISSUE THREAD

**Issue by dadeex** [lifewatch-eric/ecoportal_web_ui#75]
Is it possible to enable the field fulfillment check at any page of the submission form, before the opening of the next page of the form, instead of at the end of the three pages?
<img width="572" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/d7faa6d3-764a-42c1-8741-ab0edb41753d">
<img width="572" alt="image" src="https://github.com/lifewatch-eric/ecoportal_web_ui/assets/59953068/9c5f7e85-34f5-4dad-824c-8d16cfa978ad">

**Comment by syphax-bouazzouni** [comment]
Complex to do, moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/699  to be discussed.
