### ISSUE TITLE
"Visualization" tab not working for thesauri

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#76]
Is it normal that the "Visualization" tab doesn't show the hierarchical view of a thesaurus?

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/357eb270-ef93-4864-adbe-d50b12f7430a)

**Comment by syphax-bouazzouni** [comment]
This component has not worked, for a long time, but it does work sometimes so we did not remove as we don't have a replacement yet. 
Moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/700, to see if can be fixed as it do work in BioPortal  but not in AgroPortal.

@martinaPulieri do you want me to hide that tab?

**Comment by syphax-bouazzouni** [comment]
in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/de89e7566061a0f4df852a4a223c7e85b4ccfd0b, I hid the tab visualization in the UI until we fix it in a future release (follow up here: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/700)
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/7c83ea23-1eef-4b6f-8ece-3733facb012d">
