### ISSUE TITLE
Multilingualism function doesn't work 

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#77]
We have uploaded again the Biodiversity Thesaurus, which has labels both in the french and english. In the metadata we have declared that there are those two languages, but when we select French, the labels remain in english.

![image](https://github.com/lifewatch-eric/ecoportal_web_ui/assets/149166663/b88ec4eb-ce52-4628-abce-75b3d5b3fe2f)

Do we have to do soemthing else?

**Comment by syphax-bouazzouni** [comment]
You can check again

**Comment by martinaPulieri** [comment]
Now it works
