### ISSUE TITLE
O’FAIRe not working

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#78]
Both in development
![image](https://github.com/user-attachments/assets/9994115b-78a7-44b4-8db3-1994fc91ce29)

and production machines
![image](https://github.com/user-attachments/assets/18483063-3556-462d-8e4c-cb9abebc91e8)

the O'FAIRe tool doesn't work

**Comment by syphax-bouazzouni** [comment]
it is back on itself, each night the service restarts and refreshes the cache, and sometimes the restarts fail; waiting for the next restart fix generally the issue. 
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/aafbc7aa-38a6-4b03-bfba-bd3e007ece5a">
