### ISSUE TITLE
Concept schemes are not shown always with their labels

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#79]
I deployed this more structured thesaurus from VocBench. In the first concepts the Concept schemes are shown with their label.

![image](https://github.com/user-attachments/assets/da437993-b950-4f93-a980-e33b15fe0f2c)

When clicking on another concept, the label is not shown anymore.

![image](https://github.com/user-attachments/assets/4645d391-4d13-41dd-9cac-c086a4216e08)

**Comment by syphax-bouazzouni** [comment]
Yes, we noticed this issue https://github.com/agroportal/project-management/issues/480, will be fixed in the next releases (pinging @Bilelkihal to add it in his priorities)

**Comment by syphax-bouazzouni** [comment]
Fixed in #99 

[Screencast from 2024-11-05 04-43-10.webm](https://github.com/user-attachments/assets/d5f4253e-21ec-45d7-96f8-32797fcfa2a9)

**Comment by martinaPulieri** [comment]
It is best if the concepts that do not belong to the concept scheme selected are not shown.

**Comment by syphax-bouazzouni** [comment]
> It is best if the concepts that do not belong to the concept scheme selected are not shown.

@martinaPulieri maybe reopened this issue https://github.com/lifewatch-eric/ecoportal_web_ui/issues/80 would be the correct one, no?

**Comment by martinaPulieri** [comment]
sorry, I commented in the wrong page. I will reopen the right issue
