### ISSUE TITLE
Dowload not working

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#81]
When trying to dowload a semantic resource in any format, it doesn't start leading to a generic error page.

**Comment by syphax-bouazzouni** [comment]
Fixed by Lucia by opening the API to the public https://ecoportal.lifewatchdev.eu:8443/
![image](https://github.com/user-attachments/assets/269efed2-7972-4347-9749-3407fed5f9dd)
