### ISSUE TITLE
Issue with the text inside the Mapping table

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#82]
Why the content of the mapping table looks like this?
![image](https://github.com/user-attachments/assets/0418990b-c5ed-4641-91fa-aee97adad714)

In the production version fits well in the table
![image](https://github.com/user-attachments/assets/5da6b6af-109f-433e-818a-dad2b89c231c)

**Comment by syphax-bouazzouni** [comment]
FYI @galviset and  @Bilelkihal

**Comment by galviset** [comment]
There is ongoing work to fix this: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/687
@Bilelkihal We can see the old UI uses all the available width of the page. On top of Clément's requests for table change, shouldn't we also increase the width of the right column when displaying classes/concepts ?

**Comment by jonquet** [comment]
We trust you @galviset to come with the best layout for this table ;) @Bilelkihal may  the structure of other tables where we used icons.

**Comment by syphax-bouazzouni** [comment]
We have done a new UI for the mappings table, and added documentation on hover for each of the mapping types, see details and more screenshots in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/798
![image](https://github.com/user-attachments/assets/6ad5bf7a-9ff2-4e36-9b4e-eaa66eb85387)
