### ISSUE TITLE
Change link to metadata guidelines

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#83]
When editing a semantic resource metadata, the link to the metadata guidelines should redirect to the documentation (https://ontoportal.github.io/documentation/user_guide/metadata_schema/EcoPortal) 

![image](https://github.com/user-attachments/assets/3908eccf-d282-4b29-8f98-eb63649fd879)

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/b01f24d6e9c2d6ce8f332c9718965251f3b37f13
![image](https://github.com/user-attachments/assets/2975ad79-bdc3-4fbe-872c-b0965a989ff5)
