### ISSUE TITLE
Creator accordion

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#84]
In this resource (https://ecoportal.lifewatchdev.eu/ontologies/ENDEMISMS), there is just one creator, why there is that box beside "Fabio Cianferoni"?

![image](https://github.com/user-attachments/assets/db1e4dc9-80a5-4dc2-81ca-49a47a5bb60d)

**Comment by syphax-bouazzouni** [comment]
Fixed, there was a creator with an empty name, I edited the submission to remove it.  
![image](https://github.com/user-attachments/assets/370d65da-bfc1-4ecc-85c2-1bdc804d4c0d)
