### ISSUE TITLE
no semantic resources in projects

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#85]
I tried to add semantic resources to a project (https://ecoportal.lifewatchdev.eu/projects/LW%20ITA%20Data%20Portal), but they were not visibile when i save my actions.

![image](https://github.com/user-attachments/assets/488258ab-72c3-491b-92e5-c07cdf38bd8d)

![image](https://github.com/user-attachments/assets/5ed43103-9797-4fa8-8c83-be0774848ba4)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/790
![image](https://github.com/user-attachments/assets/0df7f30a-c2a1-4f14-82e9-0bc8632daa77)
