### ISSUE TITLE
Unable to upload a big semantic resource

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#86]
I've been trying to upload AGROVOC, but the upload stops always here.

![image](https://github.com/user-attachments/assets/e1346450-697d-4099-99c7-7746c608fd6f)

**Comment by jonquet** [comment]
Indeed, loading and parsing AGROVOC took us a little time in AgroPortal. Because this is a very big resource. 
This is a really the core  ressource for AgroPortal, so we did it. 
Is this really needed into EcoPortal ?
With the federation you guys will see results afterwards.

**Comment by martinaPulieri** [comment]
Another type of error occured, this time trying to upload a different (equally big) semanti resource.

![image](https://github.com/user-attachments/assets/c90d990b-116e-4d3e-93ae-2dd43bfb77b1)

**Comment by martinaPulieri** [comment]
@syphax-bouazzouni we are blocked in the testing because of this issue. We have the same problem in both production and development machines.

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri, can you give me a link to the file, so that I can test it on my side? 
You can also try it at https://stageportal.lirmm.fr, to see if it is specific to EcoPortal or more generic to OntoPortal.

**Comment by IlariaRosati** [comment]
https://www.chemfont.ca/system/downloads/1.0/chemfont.owl.zip

**Comment by IlariaRosati** [comment]
Hi Syphax,
I also uploaded the ChemFOnt ontology on https://stageportal.lirmm.fr/. When I will receive the email notification of the end of processing, I will report the result.

**Comment by IlariaRosati** [comment]
This is the result of the uploading:

Error_rdf

Please contact sifrportal-support@lirmm.fr if you have questions.

The ontology can be [browsed in Stageportal](http://stageportal.lirmm.fr/ontologies/CHEMFONT?invalidate_cache=true).

Thank you,
The Stageportal Team

**Comment by syphax-bouazzouni** [comment]
Hello @IlariaRosati, @martinaPulieri, 

1- When submitting the file in EcoPortal dev did you receive the parsing error notification after some minutes, as in Stageportal, as bellow ? or you had just an error message directly after submitting the file.  
> This is the result of the uploading:
> 
> Error_rdf
> 
> Please contact [sifrportal-support@lirmm.fr](mailto:sifrportal-support@lirmm.fr) if you have questions.
> 
> The ontology can be [browsed in Stageportal](http://stageportal.lirmm.fr/ontologies/CHEMFONT?invalidate_cache=true).
> 
> Thank you, The Stageportal Team

2- When I tried to open the file in https://www.chemfont.ca/system/downloads/1.0/chemfont.owl.zip
 using Protege, to test its validity as we the same parser as them, it show this error in the original file.  In summary it says that the URI used in line 353688 `http://purl.obolibrary.org/obo/3-Hydroxy-2-methyl-[S-(R,R)]-butanoic acid` is not valid. 

![image](https://github.com/user-attachments/assets/12ae0876-b127-4d49-8462-30f6b5484ff4)

**Comment by syphax-bouazzouni** [comment]
> Hello @IlariaRosati, @martinaPulieri,
> 
> 1- When submitting the file in EcoPortal dev did you receive the parsing error notification after some minutes, as in Stageportal, as bellow ? or you had just an error message directly after submitting the file.
> 
> > This is the result of the uploading:
> > Error_rdf
> > Please contact [sifrportal-support@lirmm.fr](mailto:sifrportal-support@lirmm.fr) if you have questions.
> > The ontology can be [browsed in Stageportal](http://stageportal.lirmm.fr/ontologies/CHEMFONT?invalidate_cache=true).
> > Thank you, The Stageportal Team
> 
> 2- When I tried to open the file in https://www.chemfont.ca/system/downloads/1.0/chemfont.owl.zip using Protege, to test its validity as we the same parser as them, it show this error in the original file. In summary it says that the URI used in line 353688 `http://purl.obolibrary.org/obo/3-Hydroxy-2-methyl-[S-(R,R)]-butanoic acid` is not valid.
> 
> ![image](https://private-user-images.githubusercontent.com/29259906/387694275-12ae0876-b127-4d49-8462-30f6b5484ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTE3NTIsIm5iZiI6MTczMzg5MTQ1MiwicGF0aCI6Ii8yOTI1OTkwNi8zODc2OTQyNzUtMTJhZTA4NzYtYjEyNy00ZDQ5LTg0NjItMzBmNmI1NDg0ZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA0MzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNWU2YTIxZTM5MGVlZDNjOTFmZmQ1MjAyZjAwMTRhMzViZDVhMjU3MWMwOTU0NzFmMDRlNGUyMjQzOTU2NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BdHOLdXZsZ7LDc_B1KTUCnORqXGUDZ_u6hvLXV-mPAY)

@martinaPulieri @IlariaRosati  AGROVOC did parse, what do we do for chemfont ? we can edit the problematic line and try again the submission.

**Comment by martinaPulieri** [comment]
We noticed that the line you point out is repeated several time throughout the resource, so most probably, when we fix this line, other errors will occur.

**Comment by syphax-bouazzouni** [comment]
> We noticed that the line you point out is repeated several time throughout the resource, so most probably, when we fix this line, other errors will occur.

@martinaPulieri , yeah it is true I created a script to clean and escape the wrong URIs over all the file and submitted it to thhttps://stageportal.lirmm.fr/ontologies/CHEMFONT. Do you want me to submit it too to EcoPortal ?

**Comment by martinaPulieri** [comment]
yes, please.

**Comment by syphax-bouazzouni** [comment]
> yes, please.

@martinaPulieri, done
![image](https://github.com/user-attachments/assets/f99114ac-580c-438d-84eb-6a12daf5e677)

I opened a new issue https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/893 to resolve in the futur the issue of uploading big files through the UI.
