### ISSUE TITLE
Twitter icon

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#87]
Change the Twitter icon with the new X icon

![image](https://github.com/user-attachments/assets/ecc60bde-55ed-4359-89b6-88f6c381784b)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/7a223b8e172a2da75d12f7cd738912f08f4b174a
![image](https://github.com/user-attachments/assets/3ee05714-1e95-4b26-8272-16a196dcacf2)
