### ISSUE TITLE
Send feedback doesn't work

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#88]
The email when an issue occur doesn't arrive at semantics@lifewatch.eu.

**Comment by martinaPulieri** [comment]
I have submitted a feedback. It never arrived to the email semantics@lifewatch.eu


![image](https://github.com/user-attachments/assets/46a21d93-290f-40e1-9f59-ecbb5e6ec705)

**Comment by syphax-bouazzouni** [comment]
@martinaPulieri just for information does it work in the old version?  https://ecoportal.lifewatch.eu/.

**Comment by syphax-bouazzouni** [comment]
@martinaPulieri Lucia gave me the new Lifewatch email server credentials, and it should work now.

![image](https://github.com/user-attachments/assets/a11e1a2e-653f-4551-be95-514cd518b83a)
