### ISSUE TITLE
Typo for ARDC RVA

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#89]
There is a typo when selecting the "ARDC RVA", which is indicated as "ANDV RVA"

![image](https://github.com/user-attachments/assets/ff999006-09bf-44a1-880e-dd69ec60780d)

**Comment by syphax-bouazzouni** [comment]
Hello @martinaPulieri which ontology is this?

**Comment by martinaPulieri** [comment]
Hi @syphax-bouazzouni, is not an ontology, is a semantic catalogue. It is supposed to be the ARDC Research Vocabularies Australia.

**Comment by syphax-bouazzouni** [comment]
ah OK, I see now.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ontologies_linked_data/commit/26a95d86819fd138870dc7581be268f062c425a1
![image](https://github.com/user-attachments/assets/aee9fc4e-473f-4fe1-b5d4-8e01e80a6094)
