### ISSUE TITLE
404:error in "Semantic Resource Administration"

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#91]
When trying to generate the report, a 404:error occurs.

![image](https://github.com/user-attachments/assets/23c1bf0c-2638-423e-a74b-ee384eec46c7)

**Comment by syphax-bouazzouni** [comment]
did not change anything but seems to work for me, can you try again @martinaPulieri 
![image](https://github.com/user-attachments/assets/a7d48154-c620-4c00-b3f4-e4ec7f1c611a)
