### ISSUE TITLE
Links that are non functioning

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#92]
In the footer, the links to the API and to the SPARQL endpoint are not functioning.

**Comment by syphax-bouazzouni** [comment]
API link issue fixed here https://github.com/lifewatch-eric/ecoportal_web_ui/issues/81
SPARAL endpoint removed from the EcoPortal footer, works only for Agroportal.
![image](https://github.com/user-attachments/assets/c828f107-871d-4d95-a20e-86c39fd502a2)

**Comment by martinaPulieri** [comment]
the SPARQL endpoint is still visible
![image](https://github.com/user-attachments/assets/99fe7719-6356-44ab-927d-c2ed7ff0c0d9)

**Comment by syphax-bouazzouni** [comment]
yeah sorry @martinaPulieri , now it is deployed https://ecoportal.lifewatchdev.eu/
![image](https://github.com/user-attachments/assets/a424ca28-a0cb-4fb9-8346-df3c3bcf860f)

You can close when confirmed.
