### ISSUE TITLE
In "Create project" add title to selection box

### ISSUE THREAD

**Issue by martinaPulieri** [lifewatch-eric/ecoportal_web_ui#93]
In "Create project" add a title to the box where users can select semantic resources. 

Suggested title: "Semantic resource used within the project".

![image](https://github.com/user-attachments/assets/0bc2b8ec-3f0f-4ff8-ac87-633b79ece4db)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/lifewatch-eric/ecoportal_web_ui/commit/07a2bf4465187a7550c0993ac06cc028358300bd
![image](https://github.com/user-attachments/assets/006bcb99-b403-496a-bf52-a494552ac196)
