### ISSUE TITLE
Annotator Services Returning Errors

### ISSUE THREAD

**Issue by Ramezani-07** [lifewatch-eric/ecoportal_web_ui#95]
Description: The Annotator service is not functioning properly when submitting free text for annotation. Upon submission, the following error message is displayed:

Error: "We're sorry but something has gone wrong. We have been notified of this error."

In addition, when using the Recommender service to retrieve the recommended classes and then trying to use the Annotator service with the same text, the same error message appears.

Steps to Reproduce:
Open the Annotator service.
Input free text and attempt to retrieve an annotation.
Observe the error message.
Navigate to the Recommender service.
Insert your keyword or free text in the input field.
Click on "Get recommendation."
Retrieve the recommended classes.
Click "Call Annotator with the same input."
Observe the same error message.

Expected Behavior: Both the Annotator and Recommender services should return the expected annotations and recommendations without errors.

**Comment by syphax-bouazzouni** [comment]
Can you give us the text that you used in the annotator
![image](https://github.com/user-attachments/assets/99c62f87-768a-4d43-9b50-44f72750c62a)

**Comment by syphax-bouazzouni** [comment]
@Ramezani-07  ?

**Comment by Ramezani-07** [comment]
The Annotator is working now (sometimes I get an error but generally it works). 
I used random text for testing like following:
Observation is the action or process of closely observing and monitoring something or someone.
