### ISSUE TITLE
SPARQL Endpoint and API Access Not Working from Artifact Summary Page

### ISSUE THREAD

**Issue by Ramezani-07** [lifewatch-eric/ecoportal_web_ui#96]
Description: The SPARQL endpoint and API links for specific resources submitted to the catalog are not functioning as expected. After using the Browse service and accessing a specific artifact, the buttons on the summary page, which should redirect users to the SPARQL endpoint and API for the resource, do not work.

However, it's important to note that the SPARQL endpoint for each resource is still accessible and fully functional when using the dedicated "Sparql" tab found on the individual resource’s web page.

Steps to Reproduce:
Use the Browse service to navigate to a specific resource in the catalog.
On the artifact’s summary page, attempt to use the SPARQL endpoint and API access buttons.
Observe that the buttons do not function.
Navigate to the resource’s dedicated web page.
Access the SPARQL endpoint using the "Sparql" tab.
Confirm that the endpoint is working from the tab.

Expected Behavior: The buttons on the artifact summary page should correctly redirect to the SPARQL endpoint and API for each resource.

**Comment by syphax-bouazzouni** [comment]
the API access button  is fixed see https://github.com/lifewatch-eric/ecoportal_web_ui/issues/81
