### ISSUE TITLE
Missing Domain and Range Specification for OWL Object Properties

### ISSUE THREAD

**Issue by Ramezani-07** [lifewatch-eric/ecoportal_web_ui#97]
Description: The correct representation of ontologies, a critical aspect of formalized artifact levels, is currently inadequate, particularly in terms of OWL owl:ObjectProperty. These Object Properties are essential for explicitly defining the relationships and directional connections between classes, through the use of domain and range specifications.

However, within the properties tab of each submitted resource, the domain and range for each Object Property are not being specified. This omission affects the ability to clearly understand and represent the relations between classes within the model.

Steps to Reproduce:
Navigate to a resource that contains an ontology in the catalog.
Open the properties tab for a specific owl:ObjectProperty.
Observe that the domain and range of the Object Property are not specified.

Expected Behavior: The domain and range of each Object Property should be clearly displayed in the properties tab, providing explicit representation of the relationships between the connected classes.

**Comment by syphax-bouazzouni** [comment]
Done in #98 

Example: https://ecoportal.lifewatchdev.eu/ontologies/PCO?p=properties&propertyid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000053
![image](https://github.com/user-attachments/assets/ec0c2e4e-2c28-4b3f-a74c-5ca549a3ff0f)
